targets:
  $default:
    builders:
      snow:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/gen_*

builders:
  snow:
    target: ":snow"
    import: "package:snow/builder.dart"
    builder_factories: ["snowGenerator"]
    build_extensions: {".dart": [".snow.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["json_serializable|json_serializable"]