targets:
  $default:
    builders:
      snow_generator:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/gen_*

builders:
  snow_generator:
    target: ":snow_generator"
    import: "package:snow_generator/builder.dart"
    builder_factories: ["copyWith", "toString"]
    build_extensions: {".dart": [".snow.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["json_serializable|json_serializable"]